### ISSUE TITLE
Render refactor

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/nimble#100]
It would be good to:

1.  Move `get_render` out of the `Shelf` class and just have it as a function so that it can be called with any object without need to have a shelf.

2. For each self have a list of renders for each shelf. This should be the filename and the parameters for this render. This way we are setting which renders are done inside the shelf object. This way we should be able to do something like `shelf.list_renders()` to get a list of the file names it renders, and `shelf.generate_renders()` to generate all renders to file.

**Comment by jmwright** [comment]
@julianstirling I created a fresh environment by running `pip install -e .` from the root of this repo, and then ran `cadorchestrator serve`. When I pull the page up, this is what I see.

![Screenshot from 2024-11-05 10-27-08](https://github.com/user-attachments/assets/98d3183f-6f8b-4186-8660-3c8f46fc198b)

Here's the stack trace from the server side.
```bash
$ cadorchestrator serve
INFO:     Started server process [9582]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:46610 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:46616 - "GET /assets/index-BkcDOh0u.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:46610 - "GET /assets/index-BlqZWYvB.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:46616 - "GET /get-config-options HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/cadorchestrator/server/server.py", line 183, in get_config_options
    with open(SETTINGS.configuration_options, 'r', encoding='utf-8') as component_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'OrchestratorConfigOptions.json'
```

**Comment by julianstirling** [comment]
Ah yes. From a fresh install you need to run `gen_nimble_conf_options`, this will parse the JSON of the database to create the question interface
